### PR TITLE
initialize migrate to hasura.io

### PR DESCRIPTION
**Pull request by RiskyFeryansyahP**
Migrate API to hasura

### CODE REVIEW

**Comment by RiskyFeryansyahP** [comment]
i've been this apps to hasura, please review or check this before merged @hellowin @h4ckm03d

**Comment by RiskyFeryansyahP** [comment]
@hellowin do we need remove the folder `/api`, or we just keep it like that ?
because the name folder of this hasura is `/api-hasura`

**Comment by hellowin** [comment]
Remove it

**Comment by RiskyFeryansyahP** [comment]
@hellowin, can you please help me to turn off checklist required of test go in setting ?
Because if we used hasura we dont need it workflow again.

I can't merge this pull request because need check test required, or you can force merge this pull request

**Comment by hellowin** [comment]
Done @RiskyFeryansyahP , merge it

**Pull request merged**
